### ISSUE TITLE
Improving web app experience 

### ISSUE THREAD

**Issue by jacobsamo** [jacobsamo/BuzzTrip#28]
# Improving BuzzTrip's web app
While the current web app is great there are a few bugs and improvements that can be made, along with this the following can be completed/worked on:
- #8 
- #12 
- #2 

## TODO
- [x] Add #8 
- [x] Improve metadata

### Improvements
- [x] Add create collection button on mobile drawer
- [ ] Style up landing page
- [ ] Style maps page

### Bugs
- [X] Can't create collections on the mobile
- [X] Little errors when creating markers
