### ISSUE TITLE
Business portal

### ISSUE THREAD

**Issue by jacobsamo** [jacobsamo/BuzzTrip#29]
# Business portal 
When looking through POI data on OSM, a lot of business usually small local business don't show up on the OSM map correctly with filled out information, this limits data in many map services. 
These business usually will have the google business profile all setup which is great for google maps however lacks to other services. 

## Proposal 
Creating a full-featured business profile manager which will go and create a business profile to all the major sites e.g: Google Business Profile, Trip Advisor, YELP and more. This will be provided free of charge helping the greater community/travellers looking for places.

In this app we will not only go and create business profiles on these sites up also update the map data for their business through OSM, filling out critical information like phone number, website, etc. 

This will further fill out BuzzTrip's data along with OSM data. 

This app will be it's own application and live under `business.buzztrip.co` separating it from BuzzTrip's main application but keeping them together in a way.

## Quick overview of features:
To provide a powerful experience to users we will allow them to edit in 1 spot and update everywhere, allowing less hassle of business owners to do this manually along with this they will be able to manage comments, reviews and more from all platforms. 
- Add and manage photos 
- Manage reviews from all platforms

Design idea:
![image](https://github.com/user-attachments/assets/323d98ca-4540-4de3-9778-9b16c587da9f)

## TODO
- [ ] Create Google Business Profile
- [ ] Create Trip Advisor Profile
- [ ] Manage reviews from multiple sources
- [ ] Upload photos to all profiles
- [ ] Manage business details e.g menu, website, phone, etc and update to all platforms
