### ISSUE TITLE
Implement First release features & fix bus

### ISSUE THREAD

**Issue by jacobsamo** [jacobsamo/BuzzTrip#9]
In this issue it will fix all bus in #7 and implement all features in the first release and rebuilding the things in google maps besides possible directions

## TODO
- [ ] CRUD of maps
- [ ] clicking on the map to open details e.g interesting spot (open as if it was a normal location), setting a marker, etc
- [ ] select location of the trip in map creation 
- [x] CRUD of markers
- [x] Markers bring in alot of information: pretty much everything that google maps brings in 
- [x] clicking on a marker will take you to it on the map
- [x] CRUD of collections

[Solutions library to implement certain things](https://console.cloud.google.com/google/maps-apis/build?project=my-maps-407918)

### Rebuilding what is in google my maps
- [ ] customisation of maps
- [ ] add in directions to your map
![image](https://github.com/Eirfire/BuzzTrip/assets/77374574/8911f698-44de-4c6d-997e-7aa164c62cab)
- [x] customisation of markers
- [x] customisation of collections
